// Resolves responsive image variants generated by `npm run images:gen`.
//
// `srcsetFor('fireplace02', { format: 'avif', widths: [480, 960, 1440] })`
// returns the srcset/src URLs Vite produced for the variant files sitting
// next to the source image. Missing widths are silently skipped so a partial
// generation still works.

const variants = import.meta.glob(
  '/src/assets/**/*-{480,960,1440}.{avif,jpg,jpeg}',
  { eager: true, import: 'default' }
)

const findVariant = (name, width, ext) => {
  const suffix = `/${name}-${width}.${ext}`
  for (const key of Object.keys(variants)) {
    if (key.endsWith(suffix)) return variants[key]
  }
  return null
}

export function srcsetFor(name, { widths = [480, 960, 1440], format = 'avif' } = {}) {
  const ext = format === 'jpeg' ? 'jpg' : format
  const entries = widths
    .map((w) => {
      const url = findVariant(name, w, ext)
      return url ? { w, url } : null
    })
    .filter(Boolean)
  if (entries.length === 0) {
    return { srcset: '', src: '', type: '' }
  }
  return {
    srcset: entries.map((e) => `${e.url} ${e.w}w`).join(', '),
    src: entries[Math.floor(entries.length / 2)].url,
    type: format === 'avif' ? 'image/avif' : 'image/jpeg',
  }
}
